"""
TeamFinder — Advisor chat backend.

The advisor reply is generated by an external language-model API when
configured (ANTHROPIC_API_KEY); otherwise a rule-based fallback is used so
the UI stays functional without external dependencies. User-facing strings
do not name the underlying provider; the technology is documented in the
About / Terms page.
"""

import os
from typing import Any, Dict, List, Optional

try:
    import anthropic
    _LM_AVAILABLE = True
except ImportError:
    _LM_AVAILABLE = False

_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
_MAX_HISTORY = 6
_MODEL = os.getenv("ADVISOR_MODEL", "claude-sonnet-4-20250514")


def _build_system_prompt(profile: Optional[Dict[str, Any]]) -> str:
    base = (
        "You are the TeamFinder Advisor, an in-app helper for a university "
        "team-matching platform. Help the student understand their "
        "compatibility scores, close skill gaps, navigate the projects "
        "board, and complete their profile. Keep replies practical and "
        "under 150 words unless the student explicitly asks for more depth."
    )
    if not profile:
        return base

    skills_summary = ", ".join(
        f"{s} (Lv.{l})" for s, l in (profile.get("skills") or {}).items()
    ) or "none recorded yet"

    return (
        base
        + "\n\nStudent profile:\n"
        f"  Major: {profile.get('major', 'unknown')}\n"
        f"  Skills: {skills_summary}\n"
        f"  Weekly availability: {profile.get('availability_hours', '?')} hours\n"
        f"  Bio: {profile.get('bio') or 'not provided'}\n"
        "Use this context to personalise advice when relevant."
    )


def _trim_history(history: List[Dict[str, str]]) -> List[Dict[str, str]]:
    if len(history) <= _MAX_HISTORY:
        return history
    trimmed = history[-_MAX_HISTORY:]
    if trimmed and trimmed[0].get("role") != "user":
        trimmed = trimmed[1:]
    return trimmed


def get_advisor_reply(
    message: str,
    profile: Optional[Dict[str, Any]],
    conversation_history: List[Dict[str, str]],
) -> str:
    """Return the advisor's reply; fall back to rules on any error."""
    if not _LM_AVAILABLE or not _API_KEY:
        return _fallback(message, profile)

    try:
        client = anthropic.Anthropic(api_key=_API_KEY)
        messages = _trim_history(conversation_history) + [
            {"role": "user", "content": message}
        ]
        response = client.messages.create(
            model=_MODEL,
            max_tokens=400,
            system=_build_system_prompt(profile),
            messages=messages,
        )
        return response.content[0].text
    except Exception as exc:
        print(f"[Advisor] external service error: {exc}")
        return _fallback(message, profile)


# Public alias kept for backwards-compatibility with any external imports.
def get_ai_response(message, profile, conversation_history):
    return get_advisor_reply(message, profile, conversation_history)


def _fallback(message: str, profile: Optional[Dict]) -> str:
    msg = message.lower()

    if any(w in msg for w in ("skill", "improve", "learn", "study")):
        if profile and profile.get("skills"):
            weakest = min(profile["skills"], key=profile["skills"].get)
            return (
                f"Looking at your profile, '{weakest}' is your lowest-rated "
                "skill. A focused short course or a project on the Projects "
                "board that exercises it would lift your match quality fast."
            )
        return (
            "Complete your profile and take a couple of skill exams first — "
            "that unlocks personalised recommendations."
        )

    if any(w in msg for w in ("match", "teammate", "team", "find")):
        return (
            "Match scores come from comparing your skill vector with each "
            "other student's using cosine similarity, with a small bonus "
            "for similar weekly availability. Add more verified skills to "
            "improve who you match with."
        )

    if any(w in msg for w in ("project", "guide", "kaggle", "github")):
        return (
            "The Projects board pulls in opportunities from GitHub, Kaggle, "
            "HuggingFace and CTFtime in addition to student-posted projects. "
            "Filter by a skill you want to grow."
        )

    if any(w in msg for w in ("exam", "test", "verify")):
        return (
            "Skill exams are short multiple-choice tests. Your score maps "
            "to a proficiency level (0–5). Verified skills carry more weight "
            "in matching than self-reported ones."
        )

    return (
        "I can help with skill development, understanding your match "
        "scores, or finding the right project to join. What would you "
        "like to dig into?"
    )
